# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-07 14:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patienteducator', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='doc',
            new_name='docfile',
        ),
    ]
