# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-07 19:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import patienteducator.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('patienteducator', '0002_auto_20160707_1415'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPatientDocsURL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shortened_url', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='patient',
            name='photo',
        ),
        migrations.AlterField(
            model_name='document',
            name='docfile',
            field=models.FileField(upload_to=patienteducator.models.user_directory_path),
        ),
        migrations.AddField(
            model_name='userpatientdocsurl',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patienteducator.Patient'),
        ),
        migrations.AddField(
            model_name='userpatientdocsurl',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='userpatientdocsurl',
            unique_together=set([('user', 'patient')]),
        ),
    ]
